# Generated by Django 5.2.4 on 2025-07-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='genre_list',
            field=models.TextField(default=list),
        ),
    ]
