# Generated by Django 5.2.4 on 2025-07-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='completed',
        ),
    ]
